package io.lumstudio.yohub.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF894587)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD6F8)
val md_theme_light_onPrimaryContainer = Color(0xFF37003A)
val md_theme_light_secondary = Color(0xFF6D5869)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF6DBEF)
val md_theme_light_onSecondaryContainer = Color(0xFF261625)
val md_theme_light_tertiary = Color(0xFF825247)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDAD2)
val md_theme_light_onTertiaryContainer = Color(0xFF321109)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1A1D)
val md_theme_light_outline = Color(0xFF7F747C)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF2)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFCABF6)
val md_theme_light_surfaceTint = Color(0xFF894587)
val md_theme_light_outlineVariant = Color(0xFFD1C3CC)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF7FA)
val md_theme_light_onSurface = Color(0xFF1E1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEDDEE8)
val md_theme_light_onSurfaceVariant = Color(0xFF4E444B)

val md_theme_dark_primary = Color(0xFFFCABF6)
val md_theme_dark_onPrimary = Color(0xFF531355)
val md_theme_dark_primaryContainer = Color(0xFF6E2C6E)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD6F8)
val md_theme_dark_secondary = Color(0xFFD9BFD3)
val md_theme_dark_onSecondary = Color(0xFF3C2B3A)
val md_theme_dark_secondaryContainer = Color(0xFF544151)
val md_theme_dark_onSecondaryContainer = Color(0xFFF6DBEF)
val md_theme_dark_tertiary = Color(0xFFF6B8A9)
val md_theme_dark_onTertiary = Color(0xFF4C261C)
val md_theme_dark_tertiaryContainer = Color(0xFF663B31)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDAD2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1A1D)
val md_theme_dark_onBackground = Color(0xFFE9E0E4)
val md_theme_dark_outline = Color(0xFF9A8D96)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1A1D)
val md_theme_dark_inverseSurface = Color(0xFFE9E0E4)
val md_theme_dark_inversePrimary = Color(0xFF894587)
val md_theme_dark_surfaceTint = Color(0xFFFCABF6)
val md_theme_dark_outlineVariant = Color(0xFF4E444B)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF161215)
val md_theme_dark_onSurface = Color(0xFFCDC4C8)
val md_theme_dark_surfaceVariant = Color(0xFF4E444B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD1C3CC)


val seed = Color(0xFF995996)
